### ISSUE TITLE
null-safety update

### ISSUE THREAD

**Issue by mfo33** [nbspou/dospace#13]
hey guys,

any plans to update to null safety?

**Comment by kaetemi** [comment]
Looking for someone to maintain this package

**Comment by salihgueler** [comment]
@kaetemi Will you transfer the ownership of the package?

**Comment by salihgueler** [comment]
I can take the project over if it is needed.

**Comment by kaetemi** [comment]
Ok, let's discuss in a few days.

**Comment by GraSim** [comment]
@kaetemi Will you transfer the ownership of the package? Alternatively, there seems to be an outstanding PR request for this.

**Comment by kaetemi** [comment]
I'll give access to someone who wants to maintain, yes.

**Comment by salihgueler** [comment]
I said I am willing to take over but did not receive any email from you.

**Comment by kaetemi** [comment]
Yeah, apologies. Just going through my backlog now. I'll mail you.

**Comment by GraSim** [comment]
Thanks @kaetemi

**Comment by jodinathan** [comment]
is this happening?

**Comment by salihgueler** [comment]
I will try to do coordinate this hopefully soon.

**Comment by kaetemi** [comment]
Merged.
